[package]
name = "rex-game-entities"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "2.0.0-rc.28", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
