[database]
# postgres://user:password@localhost/db_name
url = "postgres://user:password@localhost/db_name"
[identity]
app_name = "Rex Game"
client_id = "rex_game"
client_secret = "rex_game.clientsecret"
expiration = "10000000000"
refresh_expiration = "1000000000000"
[cors]
allow_origin = ["http://localhost:5173", "https://localhost:5173"]
[email]
platform_url = "https://localhost:5173"
platform_name = "Rex Game"
from_name = "Rex Game"
username = "username"
password = "password"
host = "smtp.gmail.com"
port = 587
signup_verification_url = "https://localhost:5173/account/confirm?token=[token]"
reset_password_url = "https://localhost:5173/account/reset-password?token=[token]"
